# Generated by Django 4.2.7 on 2023-12-03 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll',
            new_name='studentnumber',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
    ]
