# Generated by Django 4.2.7 on 2023-12-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_roll_student_studentnumber_remove_student_dob'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='YearLevel',
        ),
    ]
