# Generated by Django 4.2.7 on 2023-12-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_address_yearlevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='present_address',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='yearlevel',
            old_name='present_address',
            new_name='level',
        ),
    ]
