# Generated by Django 4.2.7 on 2023-12-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_student_address_alter_student_studentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentnumber',
            field=models.CharField(max_length=20),
        ),
    ]
