# Generated by Django 4.2.7 on 2023-12-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_student_studentnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlevel',
            name='level',
            field=models.CharField(max_length=255),
        ),
    ]
